# Generated by Django 4.2.6 on 2023-10-19 20:18

from django.db import migrations, models
import pgvector.django
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('vector', pgvector.django.VectorField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
